### ISSUE TITLE
使用过程无故关机

### ISSUE THREAD

**Issue by ghost** [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover#1]
您好，我的主板和您一样，cpu-9900ks.也用集显，双m.2。装黑苹果时是单硬盘安装的，搞好后装回了原来的win10 m.2硬盘。不知道怎么排查这个错误，也是黑苹果的小白，还请您理解包涵。
硬盘1.pm981a.硬盘2，金泰克2017年的一个m.2sata.没有无线网卡。pd2700u显示器驱动正常。

**Comment by ChuanfengZhang** [comment]
> 您好，我的主板和您一样，cpu-9900ks.也用集显，双m.2。装黑苹果时是单硬盘安装的，搞好后装回了原来的win10 m.2硬盘。不知道怎么排查这个错误，也是黑苹果的小白，还请您理解包涵。
> 硬盘1.pm981a.硬盘2，金泰克2017年的一个m.2sata.没有无线网卡。pd2700u显示器驱动正常。

黑苹果装在了 pm981a 硬盘上吗？这块硬盘已被证实不适合装黑苹果。

**Comment by ghost** [comment]
昨天我把故障重启的详细情况复制了一份，附到附件内，之前的不知道在哪里，所以就只有这一份，还请您分析分析，谢谢了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chuck"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 下午2:45
收件人:&nbsp;"ChuanfengZhang/Gigabyte-B365M-UHD630-Clover"<Gigabyte-B365M-UHD630-Clover@noreply.github.com&gt;;
抄送:&nbsp;"雪域"<1020793505@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover] 使用过程无故关机 (#1)





  
您好，我的主板和您一样，cpu-9900ks.也用集显，双m.2。装黑苹果时是单硬盘安装的，搞好后装回了原来的win10 m.2硬盘。不知道怎么排查这个错误，也是黑苹果的小白，还请您理解包涵。
 硬盘1.pm981a.硬盘2，金泰克2017年的一个m.2sata.没有无线网卡。pd2700u显示器驱动正常。
  
黑苹果装在了 pm981a 硬盘上吗？这块硬盘已被证实不适合装黑苹果。
