### ISSUE TITLE
启用Above 4G Decoding后点不亮了，请问下各位这个现象是个例吗？

### ISSUE THREAD

**Issue by Z-fly** [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover#10]
出厂BIOS点不亮，我更新到最新版还是点不亮。没办法只能抠电池了。
虽然不开也能黑苹果，但很多人都建议打开这项。
请问下各位这个现象是个例吗？

**Comment by ChuanfengZhang** [comment]
> 出厂BIOS点不亮，我更新到最新版还是点不亮。没办法只能抠电池了。
> 虽然不开也能黑苹果，但很多人都建议打开这项。
> 请问下各位这个现象是个例吗？

我刚试了下，开启后一切正常。

**Comment by Z-fly** [comment]
> > 出厂BIOS点不亮，我更新到最新版还是点不亮。没办法只能抠电池了。
> > 虽然不开也能黑苹果，但很多人都建议打开这项。
> > 请问下各位这个现象是个例吗？
> 
> 我刚试了下，开启后一切正常。

你的是有显卡吗？

**Comment by Z-fly** [comment]
这个和显卡有关，没有显卡的清空下开启可能就点不亮

**Comment by Z-fly** [comment]
这个和显卡有关，没有显卡的情况下开启可能就点不亮

**Comment by ChuanfengZhang** [comment]
> 这个和显卡有关，没有显卡的情况下开启可能就点不亮

用的 i5-9400 自带的集显 UHD630。BIOS 设置了使用集成显卡

独立显卡 Peripherals -- Initial Display Output -> PCIe Slot (默认自动选择) 
集成显卡 Peripherals -- Initial Display Output -> IGFX

不知道跟这个有没有关系。

**Comment by Z-fly** [comment]
大于4G地址空间的解码 用于双独立显卡下的混合交火

**Comment by Z-fly** [comment]
百度的解释是，没有独立显卡或是只有一张显卡没有打开的必要

**Comment by Z-fly** [comment]
@ChuanfengZhang 还有个问题就是现在11.3 USB要重新定制，下周二OC版本更新后，希望这里能同步更新到最新

我机型和你一样 我昨天用最新版编辑器修改保存后，重启报错，版本跨太多，升级起来很麻烦

看下这篇 https://heipg.cn/tutorial/update-efi-bootloader.html

**Comment by ChuanfengZhang** [comment]
> 百度的解释是，没有独立显卡或是只有一张显卡没有打开的必要

好嘞。

**Comment by ChuanfengZhang** [comment]
> @ChuanfengZhang 还有个问题就是现在11.3 USB要重新定制，下周二OC版本更新后，希望这里能同步更新到最新
> 
> 我机型和你一样 我昨天用最新版编辑器修改保存后，重启报错，版本跨太多，升级起来很麻烦
> 
> 看下这篇 https://heipg.cn/tutorial/update-efi-bootloader.html

又有的折腾了。。。之前我都是小版本升级，自从 0.6.7 升不上去（明明像之前一样替换了引导文件，但是 hackintool 依然显示 0.6.6）以后就没再管。

我节后回来抽时间看一下吧。

**Comment by Z-fly** [comment]
> > @ChuanfengZhang 还有个问题就是现在11.3 USB要重新定制，下周二OC版本更新后，希望这里能同步更新到最新
> > 我机型和你一样 我昨天用最新版编辑器修改保存后，重启报错，版本跨太多，升级起来很麻烦
> > 看下这篇 https://heipg.cn/tutorial/update-efi-bootloader.html
> 
> 又有的折腾了。。。之前我都是小版本升级，自从 0.6.7 升不上去（明明像之前一样替换了引导文件，但是 hackintool 依然显示 0.6.6）以后就没再管。
> 
> 我节后回来抽时间看一下吧。

升不上去的话重置一下NVRAM，重置后重新解锁一遍CFG

**Comment by ChuanfengZhang** [comment]
> > > @ChuanfengZhang 还有个问题就是现在11.3 USB要重新定制，下周二OC版本更新后，希望这里能同步更新到最新
> > > 我机型和你一样 我昨天用最新版编辑器修改保存后，重启报错，版本跨太多，升级起来很麻烦
> > > 看下这篇 https://heipg.cn/tutorial/update-efi-bootloader.html
> > 
> > 
> > 又有的折腾了。。。之前我都是小版本升级，自从 0.6.7 升不上去（明明像之前一样替换了引导文件，但是 hackintool 依然显示 0.6.6）以后就没再管。
> > 我节后回来抽时间看一下吧。
> 
> 升不上去的话重置一下NVRAM，重置后重新解锁一遍CFG

嗯嗯，今天刚看到这个解决方案。

我查了一下 11.3 USB 的问题，你有没有试过 Kernel——Quirks——XhciPortLimit，取消勾选XhciPortLimit，然后保存重启？

**Comment by Z-fly** [comment]
> > > > @ChuanfengZhang 还有个问题就是现在11.3 USB要重新定制，下周二OC版本更新后，希望这里能同步更新到最新
> > > > 我机型和你一样 我昨天用最新版编辑器修改保存后，重启报错，版本跨太多，升级起来很麻烦
> > > > 看下这篇 https://heipg.cn/tutorial/update-efi-bootloader.html
> > > 
> > > 
> > > 又有的折腾了。。。之前我都是小版本升级，自从 0.6.7 升不上去（明明像之前一样替换了引导文件，但是 hackintool 依然显示 0.6.6）以后就没再管。
> > > 我节后回来抽时间看一下吧。
> > 
> > 
> > 升不上去的话重置一下NVRAM，重置后重新解锁一遍CFG
> 
> 嗯嗯，今天刚看到这个解决方案。
> 
> 我查了一下 11.3 USB 的问题，你有没有试过 Kernel——Quirks——XhciPortLimit，取消勾选XhciPortLimit，然后保存重启？

我用你的配置，USB3.0无法使用，等新版本出来后我自己再研究一下

**Comment by ChuanfengZhang** [comment]
我做过 USB 定制，据说升级后不会失效。

**Comment by ChuanfengZhang** [comment]
> > > > > @ChuanfengZhang 还有个问题就是现在11.3 USB要重新定制，下周二OC版本更新后，希望这里能同步更新到最新
> > > > > 我机型和你一样 我昨天用最新版编辑器修改保存后，重启报错，版本跨太多，升级起来很麻烦
> > > > > 看下这篇 https://heipg.cn/tutorial/update-efi-bootloader.html
> > > > 
> > > > 
> > > > 又有的折腾了。。。之前我都是小版本升级，自从 0.6.7 升不上去（明明像之前一样替换了引导文件，但是 hackintool 依然显示 0.6.6）以后就没再管。
> > > > 我节后回来抽时间看一下吧。
> > > 
> > > 
> > > 升不上去的话重置一下NVRAM，重置后重新解锁一遍CFG
> > 
> > 
> > 嗯嗯，今天刚看到这个解决方案。
> > 我查了一下 11.3 USB 的问题，你有没有试过 Kernel——Quirks——XhciPortLimit，取消勾选XhciPortLimit，然后保存重启？
> 
> 我用你的配置，USB3.0无法使用，等新版本出来后我自己再研究一下

嗯嗯，按网上的定制教程研究一下就行。

**Comment by Z-fly** [comment]
现在可以更新一下了 @ChuanfengZhang

**Comment by ChuanfengZhang** [comment]
> 现在可以更新一下了 @ChuanfengZhang

这周比较忙，下周吧

**Comment by ChuanfengZhang** [comment]
> 现在可以更新一下了 @ChuanfengZhang

更新到 0.6.9 了，macOS 还是 11.2.2，有时间再升系统。你可以试一下。

**Comment by ChuanfengZhang** [comment]
@Z-fly 更新到 11.3.1 了，一切正常，USB 正常。

**Comment by ChuanfengZhang** [comment]
更新了 Liu，Apple ALC，WhateverGreen，忘记 push 了

**Comment by Z-fly** [comment]
@ChuanfengZhang 还有另一个issue，你看下

**Comment by ChuanfengZhang** [comment]
> @ChuanfengZhang 还有另一个issue，你看下

看到了，一个 issue 讨论一个事，不要混在一起哈
