### ISSUE TITLE
macOS Big Sur 11.0.1安装程序到第二阶段卡死

### ISSUE THREAD

**Issue by TomHeaven** [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover#11]
同款技嘉B365M主板，I5-9400 CPU，UHD630核显，用本项目OC引导，macOS Big Sur 11.0.1安装程序到第二阶段（从verbose模式进入图形界面）卡死，不出安装界面。

HDMI，DVI，DP口都试过了，感觉挺奇怪的。

**Comment by ChuanfengZhang** [comment]
> 同款技嘉B365M主板，I5-9400 CPU，UHD630核显，用本项目OC引导，macOS Big Sur 11.0.1安装程序到第二阶段（从verbose模式进入图形界面）卡死，不出安装界面。
> 
> HDMI，DVI，DP口都试过了，感觉挺奇怪的。

可以试试用黑果小兵的包安装完再替换为我的配置。

**Comment by ChuanfengZhang** [comment]
可能是 AppleCpuPmCfgLock 没有启用的原因
