### ISSUE TITLE
这块主板可以手动解锁CFG吗？

### ISSUE THREAD

**Issue by Z-fly** [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover#12]

**Comment by ChuanfengZhang** [comment]
可以的，参考黑果小兵的[这篇博文](https://blog.daliansky.net/undefined.html)，⚠️注意⚠️：CFGLOCK.efi 的下载地址更换为 https://raw.githubusercontents.com/daliansky/Hackintosh/master/Tools/CFGLOCK/CFGLock.efi

**Comment by Z-fly** [comment]
> 可以的，参考黑果小兵的[这篇博文](https://blog.daliansky.net/undefined.html)，⚠️注意⚠️：CFGLOCK.efi 的下载地址更换为 https://raw.githubusercontents.com/daliansky/Hackintosh/master/Tools/CFGLOCK/CFGLock.efi

我看到你配置里两个CFG补丁就打了一个。这是技嘉默认解锁了一半吗？

**Comment by ChuanfengZhang** [comment]
> > 可以的，参考黑果小兵的[这篇博文](https://blog.daliansky.net/undefined.html)，⚠️注意⚠️：CFGLOCK.efi 的下载地址更换为 https://raw.githubusercontents.com/daliansky/Hackintosh/master/Tools/CFGLOCK/CFGLock.efi
> 
> 我看到你配置里两个CFG补丁就打了一个。这是技嘉默认解锁了一半吗？

我是用 clover 引导，安装完使用了几个月后转到 OC 的。这两项是用的默认设置，之前还真没了解过 CFG Lock，感谢你🙏
AppleCpuPmCfgLock = No
AppleXcpmCfgLock = Yes
https://opencore.slowgeek.com/?file=coffeelake066ADlG9Z&rs=coffeelake066

**Comment by Z-fly** [comment]
AppleCpuPmCfgLock理论上也要开启，当然如果安装的时候没有问题就不用管了

**Comment by Z-fly** [comment]
IgnoreInvalidFlexRatio 在没解锁CFG的时候也可能要打开

**Comment by ChuanfengZhang** [comment]
> AppleCpuPmCfgLock理论上也要开启，当然如果安装的时候没有问题就不用管了

是的，我想起来有几位网友反馈说安装卡住，我想应该找到原因了😂

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/116678421-dfa50d00-a9db-11eb-953a-63662e2fb15f.png)
