### ISSUE TITLE
关于EFI几点设置求教？

### ISSUE THREAD

**Issue by liuxuan0218** [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover#15]
1.boot-args中darkwake=0和vsmcgen=1是什么意思，有什么作用？

2.boot-args中-lilubetaall是否可以删除？

3.prev-lang:kbd中填入的D31EDAEB CD9DE3CE B5E9EEF7 DDADF6DF 9DF6是哪国的键盘设置？为什么不是7a682d48616e733a323532中文？

4.PlatformInfo中ROM中需要填写真实的网卡MAC地址吗？有线网卡en0无线网卡en1，填写哪个？

**Comment by ChuanfengZhang** [comment]
善用搜索、大胆尝试（我也不知道，都是瞎摸索）

**Comment by liuxuan0218** [comment]
我也是搜不到信息啊，或者搜到了也看不懂，哈哈

**Comment by Z-fly** [comment]
lilubetaall是给macOS12 beta版用的
darkwake是电源管理参数 vsmcgen是SMC的参数 你删掉再启动没有影响的话，可以忽略掉
PlatformInfo没有影响，可以写11 22 33 44 55 66

**Comment by liuxuan0218** [comment]
> lilubetaall是给macOS12 beta版用的
> darkwake是电源管理参数 vsmcgen是SMC的参数 你删掉再启动没有影响的话，可以忽略掉
> PlatformInfo没有影响，可以写11 22 33 44 55 66

大神你好，某些博主提到下面这个ACPI补丁，请问需要吗？（不知是否和开机阶段跑码ACPI报错有关）机器不在身边，还没尝试，不懂先问，哈哈

SSDT-OC-XOSI.aml 操作系统补丁，配合重命名rename 5F4F5349 to 584F5349，技嘉主板需要 （作者：小明和他的女朋友 https://www.bilibili.com/read/cv6737693?spm_id_from=333.788.b_636f6d6d656e74.28 出处：bilibili）

**Comment by Z-fly** [comment]
https://blog.daliansky.net/hotpatch-detailed-solution.html

**Comment by Z-fly** [comment]
> > lilubetaall是给macOS12 beta版用的
> > darkwake是电源管理参数 vsmcgen是SMC的参数 你删掉再启动没有影响的话，可以忽略掉
> > PlatformInfo没有影响，可以写11 22 33 44 55 66
> 
> 大神你好，某些博主提到下面这个ACPI补丁，请问需要吗？（不知是否和开机阶段跑码ACPI报错有关）机器不在身边，还没尝试，不懂先问，哈哈
> 
> SSDT-OC-XOSI.aml 操作系统补丁，配合重命名rename 5F4F5349 to 584F5349，技嘉主板需要 （作者：小明和他的女朋友 https://www.bilibili.com/read/cv6737693?spm_id_from=333.788.b_636f6d6d656e74.28 出处：bilibili）

https://blog.daliansky.net/hotpatch-detailed-solution.html

**Comment by liuxuan0218** [comment]
> > > lilubetaall是给macOS12 beta版用的
> > > darkwake是电源管理参数 vsmcgen是SMC的参数 你删掉再启动没有影响的话，可以忽略掉
> > > PlatformInfo没有影响，可以写11 22 33 44 55 66
> > 
> > 
> > 大神你好，某些博主提到下面这个ACPI补丁，请问需要吗？（不知是否和开机阶段跑码ACPI报错有关）机器不在身边，还没尝试，不懂先问，哈哈
> > SSDT-OC-XOSI.aml 操作系统补丁，配合重命名rename 5F4F5349 to 584F5349，技嘉主板需要 （作者：小明和他的女朋友 https://www.bilibili.com/read/cv6737693?spm_id_from=333.788.b_636f6d6d656e74.28 出处：bilibili）
> 
> https://blog.daliansky.net/hotpatch-detailed-solution.html

这篇文章提到了使用SSDT-OC-XOSI.aml解决ACPI关于_RTC报错，网文地址：https://post.smzdm.com/p/ag8pkxdd/

引用文中语句：遇到ACPI关于_RTC报错，但系统能顺利运行的，这个_RTC错误可修复可不修复。 修复的方法为： 将SSDT-OC-XOSI.aml加入ACPI/patched/文件夹中， 并添加DSDT Patches Change _OSI to XOSI Find 5F4F5349 Replace 584F5349

**Comment by Z-fly** [comment]
这个可以让@ChuanfengZhang 去测一下，我电脑删掉黑苹果了。

**Comment by ChuanfengZhang** [comment]
> 这个可以让@ChuanfengZhang 去测一下，我电脑删掉黑苹果了。

好，我大概明天试一下

**Comment by Z-fly** [comment]
https://bbs.pcbeta.com/viewthread-1855554-1-1.html
@ChuanfengZhang @liuxuan0218 我觉得这就是解决报错的方案了

**Comment by liuxuan0218** [comment]
> https://bbs.pcbeta.com/viewthread-1855554-1-1.html
> @ChuanfengZhang @liuxuan0218 我觉得这就是解决报错的方案了

是，昨晚实测已解决ACPI报错，具体方法：将SSDT-OC-XOSI.aml加入ACPI文件夹和config中， 并添加热补丁DSDT Patches Change _OSI to XOSI Find 5F4F5349 Replace 584F5349

其实不影响系统正常加载，强迫症可以修补一下。

**Comment by Z-fly** [comment]
@ChuanfengZhang 可以修补一下吗？看到你这边还在持续更新

**Comment by ChuanfengZhang** [comment]
@liuxuan0218 @Z-fly 已修补，感谢二位。
