### ISSUE TITLE
没有电源管理怎么办?

### ISSUE THREAD

**Issue by ghost** [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover#16]
![image](https://user-images.githubusercontent.com/33117989/143805366-8bed6e66-3162-4cc0-85b9-e2f3129f248c.png)
我的配置
![image](https://user-images.githubusercontent.com/33117989/143805477-ec7eeb17-3fee-4db4-a305-50d01e7b0623.png)

**Comment by ChuanfengZhang** [comment]
更新到最新的 EFI 试试
