### ISSUE TITLE
请问解决了usb power额外电力支持的问题了吗？

### ISSUE THREAD

**Issue by bonbaobao** [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover#2]
https://medium.com/macoclock/common-problems-and-workarounds-in-hackintosh-85d76ad89d24

就是插入苹果设备会有大电流充电，https://miro.medium.com/max/1400/0*DXeVBkqeGrjYSL73.png

https://www.tonymacx86.com/threads/guide-usb-power-property-injection-for-sierra-and-later.222266/page-2

https://support.apple.com/zh-cn/HT204377

**Comment by ghost** [comment]
插入的是硬盘，刚开始有插入就关机，后来没有了，正常了。
