### ISSUE TITLE
装580 8G后核显问题

### ISSUE THREAD

**Issue by supermicah** [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover#3]
按照这个配置安装好后，增加了amd的580 8G的，免驱，并且能够待机，一切正常，但是出现了核显无法开启问题，需要怎么配置？

**Comment by ChuanfengZhang** [comment]
> 按照这个配置安装好后，增加了amd的580 8G的，免驱，并且能够待机，一切正常，但是出现了核显无法开启问题，需要怎么配置？

我恰好有独显的配置，等我回头更新一下。

**Comment by ChuanfengZhang** [comment]
> 按照这个配置安装好后，增加了amd的580 8G的，免驱，并且能够待机，一切正常，但是出现了核显无法开启问题，需要怎么配置？

@supermicah 我的 RX570 配置已经提交到 [RX570 分支](https://github.com/ChuanfengZhang/Gigabyte-B365M-UHD630-Clover/tree/RX570)，你可以试下

**Comment by ChuanfengZhang** [comment]
@supermicah 我的 RX570 配置已经提交到 [RX570 分支](https://github.com/ChuanfengZhang/Gigabyte-B365M-UHD630-Clover/tree/RX570)，你可以试下

**Comment by supermicah** [comment]
@ChuanfengZhang 我是需要重装系统么？还是只需要把整个efi替换掉就可以了

**Comment by ChuanfengZhang** [comment]
@supermicah 不需要，备份好原 EFI，然后用我的替换就好了。有问题再通过 PE 换回来。**一定要确保能通过 PE 恢复原 EFI**，不然就惨了哈

**Comment by supermicah** [comment]
@ChuanfengZhang 好的，我装了双系统，有window，如果进不了系统，是否在window下替换也是可以的？
另外一个问题是，如果我用你的EFI，是否会改变原来的序列号，因为有个软件是根据序列号来的。

**Comment by supermicah** [comment]
之前我改为iMac Pro (2017)是可以在videoproc上成功，但是不确定是否开启了核显。

**Comment by ChuanfengZhang** [comment]
@supermicah 
能打开 EFI 分区读写文件就可以；我的 EFI 包含序列号，你可以替换为自己的。
