### ISSUE TITLE
Can't run dual screen 

### ISSUE THREAD

**Issue by binhhoit** [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover#6]
HDMI display port not working and auto restart.
-- EFI run some thing normal ,thanks

**Comment by ChuanfengZhang** [comment]
> HDMI display port not working and auto restart.
> -- EFI run some thing normal ,thanks

Can you use DP port instead?

**Comment by ChuanfengZhang** [comment]
> HDMI display port not working and auto restart.
> -- EFI run some thing normal ,thanks

I'm sorry, this config has only been tested on single screen using DP port.

**Comment by ChuanfengZhang** [comment]
> HDMI display port not working and auto restart.
> -- EFI run some thing normal ,thanks

You can try my OC config. I'm using it and DP and HDMI can working together.
