### ISSUE TITLE
Not working for Gigabyte B365M DS3H

### ISSUE THREAD

**Issue by mayank-budhiraja** [ChuanfengZhang/Gigabyte-B365M-UHD630-Clover#8]
I am trying to make the similar config work on Gigabyte B365M DS3H. Not working. Any help?

**Comment by ChuanfengZhang** [comment]
> I am trying to make the similar config work on Gigabyte B365M DS3H. Not working. Any help?

I'm sorry. I only test this config on Gigabyte B365M Aorus Elite.

**Comment by shilik** [comment]
> I am trying to make the similar config work on Gigabyte B365M DS3H. Not working. Any help?
Try mine. I have the same device as yours.

[https://drive.google.com/file/d/14-SqThE5F3siHix2Yr0HhD160kMaGAxb/view?usp=sharing](url)
